### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by IADDIC** [davidlang42/taskban#8] opened 2022-05-06 16:26 UTC
Hello:  I have recently tried to access taskban online.  When taskban asks for authentication via the pop-up dialog :

TaskBan
The developer of TaskBan, [davidlang42@gmail.com](mailto:davidlang42@gmail.com), needs your permission to access your data on Google.

I then select 
review permissions:
select the account
then select allow to allow all requested permissions.

Then a spinning wheel appears quickly and then is replaced with the authorization popo up.  This is a do-loop.

**Comment by davidlang42** [comment] 2022-05-10 12:31
Hi @IADDIC,

This seems to be a duplicate of this issue: https://github.com/davidlang42/taskban/issues/1

Please see comments and explanation there.

David.

**Closed by davidlang42** 2022-05-10 12:31 UTC

**Comment by davidlang42** [comment] 2022-05-15 13:38
Hi Richard,

I can't see the error you attached, but unfortunately if its anything to do with the OAuth login, that is entirely in Google's control. My app does not do any logging in or authorisation, it relies entirely on Google's OAuth login and authorisation system, so there is nothing I can do to help. Sorry.

David.
